### ISSUE TITLE
Version 1.4.3 still uses Amplitude-iOS 3.14

### ISSUE THREAD

**Issue by ghislainfrs** [segment-integrations/analytics-ios-integration-amplitude#27]
I updated the Segment-Amplitude pod to 1.4.3 in order to have the version 4.0 of the Amplitude-iOS pod. 
In your Podspec the version of Amplitude-iOS seems to be set correctly, but when executing `pod install` or `pod update` the version which is installed is still the old 3.14...
In the [Cocoapods specs repo](https://github.com/CocoaPods/Specs/blob/087428d0d4cc5da60199f034b237965dc051075b/Specs/f/6/5/Segment-Amplitude/1.4.3/Segment-Amplitude.podspec.json), we see the version of Amplitude-iOS is still 3.14

**Comment by TimothyDavidW** [comment]
I am also experiencing this issue. 1.4.3 was released on 25th May so looks like all that is needed is new release is needed in order to have version 4.0 of the Amplitude-IOS pod. The 4.0 Amplitude-IOS pod includes ios11 updates. I am currently experiencing the following issue when running on iOS11:

Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 825, TID: 170793, Thread name: (none), Queue name: io.segment.analytics, QoS: 0
Backtrace:
4   Amplitude_iOS                       0x0000000103e8492c -[Amplitude initializeApiKey:userId:setUserId:] + 684
5   Amplitude_iOS                       0x0000000103e845b8 -[Amplitude initializeApiKey:] + 84
6   Segment_Amplitude                   0x000000010457f478 -[SEGAmplitudeIntegration initWithSettings:] + 640

I am hoping that by updating to amplitude-IOS 4.0 or above this issue will be resolved. 

Do you have any idea when this might be done?

**Comment by ladanazita** [comment]
@ghislainfrs @TimothyDavidW Sorry about that - I merged the changes but didn't cut a new release.  Let me release this now and I will ping you here when it is live.

**Update:** This is up on 1.4.4: https://cocoapods.org/pods/Segment-Amplitude#changelog

Please let me know if you continue to see any issues!

**Comment by TimothyDavidW** [comment]
Thanks for the speedy resolution @ladanazita I can confirm Amplitude-IOS 4.0.1 is now being used. 

Unfortunately I'm still getting the same error but will take this up with the amplitude guys as I am now running the latest version and it is still an issue. Thanks again.

**Comment by ghislainfrs** [comment]
Thanks for the update and your reactivity @ladanazita!
